name = "fortranpack"
version = "0.1.0"
license = "license"
author = "Jacob Williams"
maintainer = "jacobwilliams@users.noreply.github.com"
copyright = "Copyright 2025, Jacob Williams"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
link = ["lapack", "blas"]

[install]
library = true
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[library]
source-dir = "src"

[dependencies]
argv-fortran             = { git = "https://github.com/jacobwilliams/argv-fortran" }
bspline-fortran          = { git = "https://github.com/jacobwilliams/bspline-fortran" }
carlson-elliptic-integrals = { git = "https://github.com/jacobwilliams/carlson-elliptic-integrals" }
conmax                   = { git = "https://github.com/jacobwilliams/conmax" }
conmin                   = { git = "https://github.com/jacobwilliams/conmin" }
csv-fortran              = { git = "https://github.com/jacobwilliams/csv-fortran" }
daglib                   = { git = "https://github.com/jacobwilliams/daglib" }
ddeabm                   = { git = "https://github.com/jacobwilliams/ddeabm" }
dop853                   = { git = "https://github.com/jacobwilliams/dop853" }
finterp                  = { git = "https://github.com/jacobwilliams/finterp" }
fortran-mach             = { git = "https://github.com/jacobwilliams/fortran-mach" }
fortran-search-and-sort  = { git = "https://github.com/jacobwilliams/fortran-search-and-sort" }
json-fortran             = { git = "https://github.com/jacobwilliams/json-fortran" }
lbfgsb                   = { git = "https://github.com/jacobwilliams/lbfgsb" }
mersenne-twister-fortran = { git = "https://github.com/jacobwilliams/mersenne-twister-fortran" }
nlesolver-fortran        = { git = "https://github.com/jacobwilliams/nlesolver-fortran"}
NumDiff                  = { git = "https://github.com/jacobwilliams/NumDiff" }
optgra                   = { git = "https://github.com/jacobwilliams/optgra" }
pchip                    = { git = "https://github.com/jacobwilliams/PCHIP" }
pikaia                   = { git = "https://github.com/jacobwilliams/pikaia" }
polyroots-fortran        = { git = "https://github.com/jacobwilliams/polyroots-fortran" }
popen-fortran            = { git = "https://github.com/jacobwilliams/popen-fortran" }
psqp                     = { git = "https://github.com/jacobwilliams/psqp" }
pyplot-fortran           = { git = "https://github.com/jacobwilliams/pyplot-fortran" }
quadpack                 = { git = "https://github.com/jacobwilliams/quadpack" }
quadrature-fortran       = { git = "https://github.com/jacobwilliams/quadrature-fortran" }
regridpack               = { git = "https://github.com/jacobwilliams/regridpack" }
rklib                    = { git = "https://github.com/jacobwilliams/rklib" }
roots-fortran            = { git = "https://github.com/jacobwilliams/roots-fortran" }
simulated-annealing      = { git = "https://github.com/jacobwilliams/simulated-annealing" }
slsqp                    = { git = "https://github.com/jacobwilliams/slsqp" }
splpak                   = { git = "https://github.com/jacobwilliams/splpak" }
stringsort               = { git = "https://github.com/jacobwilliams/stringsort" }
uuid-fortran             = { git = "https://github.com/jacobwilliams/uuid-fortran" }
